// examples/react/src/app.jsx
import * as React from 'react';

export const App = () => {
    const [counter, setCounter] = React.useState(0);

    const startTimer = () => {
        console.log('clicked');
        setTimeout(() => {
            console.log('timeouted');
            setCounter(counter + 1);
        }, 2000);
    }

    return <div>
        <div>This is React sample</div>
        <button id="btn" onClick={startTimer}>Click Me</button>
        <div>
            Timer Completed:
      <span id="cnt">{counter}</span>
        </div>
    </div>;
}

// examples/vue/src/app.vue
<template>
  <div>
    <div>This is Vue sample</div>
    <button id="btn" v-on:click="startTimer">Click Me</button>
    <div>
      Timer Completed:
      <span id="cnt">{{ counter }}</span>
    </div>
  </div>
</template>

<script>
export default {
  name: "app",
  data: () => ({
    counter: 0
  }),
  methods: {
    startTimer: function() {
      console.log('clicked');
      setTimeout(() => {
        console.log('timeouted');
        this.counter++;
      }, 2000);
    }
  }
};
</script>
